WIP: Android IAP library projects updated
inplayer-org/applicaster-inplayer-plugin pull request #39
Opened 2020-08-14 21:39 UTC by inckie

There is new project added, iap-uni, which incapsulates access to Amazon and Google billing backends.
Other projects were renamed.
Updated @applicaster/applicaster-iap is not yet published in npm, so shis should not be merged yet.

2020-08-27 09:09 UTC, Budaa commented
@inckie Do we still need it? If so this change should only be applied to `manifest.config.json`

2020-08-27 09:09 UTC, Budaa requested changes
Should be applied to manifest.config.json only

2020-08-27 19:24 UTC, inckie commented
@Budaa yep, we need it, but after we will publish an updated version of the billing library itself. I'll fix manifest when its done.

2020-09-02 13:34 UTC, Budaa approved these changes

2020-09-02 13:40 UTC, merged